CCP4I2 to use contact file and fix of failing unitttest
rigdenlab/ample pull request #34
Opened 2017-11-07 20:57 UTC by linucks

2017-11-07 21:34 UTC, fsimkovic commented on i2/AMPLE.def.xml
> +			    	<default>casprr</default>
Could you please change this to `casp`. The code added in `ample/util/contact_util.py` disables the `casprr` option.

2017-11-07 21:38 UTC, fsimkovic requested changes

2017-11-07 21:38 UTC, fsimkovic commented on i2/AMPLE_gui.py
> +        parsers = sorted(conkit.io.CONTACT_FILE_PARSERS.keys())
The ConKit mask is now in `ample/util/contact_util.py` and should be imported from there.
```
>>> from ample.util.contact_util import CONTACT_FILE_PARSERS
>>> print(CONTACT_FILE_PARSERS)
['bbcontacts', 'bclcontact', 'casp', 'ccmpred', 'comsat', 'epcmap', 
 'evfold', 'freecontact', 'gremlin', 'membrain', 'metapsicov', 'mmcif', 
 'pconsc', 'pconsc2', 'pconsc3', 'pdb', 'plmdca', 'psicov']
```
The default, as mentioned above, should be set to `casp`.

2017-11-08 11:07 UTC, linucks commented
I've updated as per your comments.

2017-11-08 15:06 UTC, fsimkovic commented
👍  for GUI in i2!!

2017-11-08 15:08 UTC, fsimkovic approved these changes

2017-11-08 15:08 UTC, fsimkovic commented
Looks good to me. Unittests run fine 👍 .

2017-11-08 15:09 UTC, merged