Change ensembler_timeout, create constants for cluster_method and add test for construct_references
rigdenlab/ample pull request #50
Opened 2018-05-22 17:28 UTC by linucks

2018-05-22 20:25 UTC, fsimkovic requested changes

2018-05-22 20:25 UTC, fsimkovic commented on ample/ensembler/abinitio.py
> +            raise RuntimeError, "Cannot find any models for ensembling!"
Make Python3 compatible
```python
raise RuntimeError("Cannot find any models for ensembling!")
```

2018-05-22 20:25 UTC, fsimkovic commented on ample/util/argparse_util.py
> +    parser = argparse.ArgumentParser(
We should include the [`formatter_class=argparse.ArgumentDefaultsHelpFormatter`](https://docs.python.org/2/library/argparse.html#argparse.ArgumentDefaultsHelpFormatter) keyword, so `--help` calls show defined default values without us having to define them in the docstring of the argument.

2018-05-22 20:25 UTC, fsimkovic commented on ample/ensembler/__init__.py
> +from constants import SPICKER_TM
Maybe specify explicitly which constants we're important, i.e. `from ample.ensembler.constants ...`

2018-05-23 07:29 UTC, linucks commented on ample/util/argparse_util.py
> +    parser = argparse.ArgumentParser(
I'm not sure about this. We don't set defaults using argparse so this just prints lots of None's and so isn't adding anything helpful.

2018-05-23 07:30 UTC, linucks commented
Thanks for the helpful review @fsimkovic. I've pushed some additional changes

2018-05-23 07:30 UTC, fsimkovic commented on ample/util/argparse_util.py
> +    parser = argparse.ArgumentParser(
Should encourage us to change the defaults to the argparser ... but fair enough, didn't know many we set

2018-05-23 07:31 UTC, fsimkovic approved these changes

2018-05-23 07:40 UTC, merged