Update AMPLE to use pyjob
rigdenlab/ample pull request #79
Opened 2020-07-23 13:14 UTC by hlasimpk

I've intended to put a pull request in for this for a while but needed to test it. This seems to work fine on badb/barkla and locally on my machine. 

I spoke with Jens about the cluster submission options and so I've set up Pyjob to use the same options. There are a few options that I wish to deprecate (`-submit_cluster True`, `-submit_pe_sge` & `-submit_pe_lsf`). The first is now inferred from the submit_qtype option and the other 2 will be replaced with the `-submit_pe` option. 

Generally speaking I've just gone through and replaced the old code with Pyjob, this also means that the modules for submitting code to clusters/local machines has been removed.

2020-07-23 16:13 UTC, FilomenoSanchez approved these changes

2020-07-25 10:39 UTC, fsimkovic requested changes

2020-07-25 10:39 UTC, fsimkovic commented on ample/modelling/__main__.py
> +    rm.submit_cluster = True
```
rm.submit_cluster = args.submit_qtype != "local"
```

2020-07-25 10:39 UTC, fsimkovic commented on ample/testing/integration_util.py
> +        if not len(collector.scripts):
```
if not collector.scripts
```

2020-07-25 10:39 UTC, fsimkovic commented on ample/util/mrbump_util.py
> +    logger.debug("Wrote MRBUMP script: {0}".format(script.path))
should be % notation

2020-07-27 12:56 UTC, merged